version: '2'
services:
  rabbitmq:
    ports:
      - 5672:5672
      
  mysql:
      build: mysql
      
  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  webhook:
    build: webhook